spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: workspaces-api
          uri: lb://workspaces-api/workspaces/**
          predicates:
            - Path=/workspaces/**
        - id: employees-api
          uri: lb://workspaces-api/workspaces/**
          predicates:
            - Path=/workspaces/**

server:
  port:
    9094

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
