spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: workspaces-api
          uri: lb://workspaces-service/workspaces/**
          predicates:
            - Path=/workspaces/**
        - id: employees-api
          uri: lb://employees-service/employees/**
          predicates:
            - Path=/employees/**

server:
  port:
    9094

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
